### PR TITLE
add cuda 11.2.1

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Note that I am bumping the build number here, so no need to fix the [unbumped build from yesterday](https://github.com/conda-forge/cudatoolkit-feedstock/pull/52#issuecomment-777743560).

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Review by kkraus14 — APPROVED** [review]
changes LGTM, thanks @jaimergp!

**Comment by kkraus14** [comment]
I'm going to merge this, but @jaimergp would you be interested in adding yourself as a maintainer on this feedstock given the extent of the work you've been doing in this space? It's been greatly appreciated!

**Comment by jaimergp** [comment]
All good! I'll add myself in the next PR!

**Comment by jaimergp** [comment]
9.2, 11.1 and 11.2.1 did not upload correctly on Windows. Can anybody re-run those? This is already mentioned in #54 but we should still try to get these uploaded correctly.

**Pull request merged**
