### PR TITLE
Add `license_url`

### PR DESCRIPTION
**Pull request by jakirkham**
Includes the `license_url` field linking to the EULA in the recipe. Should be picked up by Anaconda.org as well.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Partially addresses issue ( https://github.com/conda-forge/cudatoolkit-feedstock/issues/2 ).

### CODE REVIEW

**Review by kkraus14 — APPROVED** [review]

**Review by isuruf — CHANGES_REQUESTED** [review]
Can you change the target label to `test` instead of `main`?

**Comment by scopatz** [comment]
> Can you change the target label to test instead of main? 

That can be another PR

**Comment by scopatz** [comment]
Thanks @jakirkham!

**Comment by isuruf** [comment]
> That can be another PR, it is a separate concern

Then please make sure that you add a `broken` label is added if this package gets published.

**Comment by jakirkham** [comment]
Ah sorry. Yeah switching label is a good idea.

**Comment by jakirkham** [comment]
Also updated this in the Anaconda.org settings for this package. This seems to link correctly now.

Screen Shot 2020-10-14 at 12 09 15 PM

**Pull request merged**
