### PR TITLE
Add cupti support

### LINKED ISSUE #40: libcupti library missing from packages
In https://github.com/conda-forge/cudatoolkit-feedstock/pull/26 it was pointed out that there was warnings from missing the `libcupti` shared library:

```
WARNING (cudatoolkit,lib/libaccinj64.so.11.1.105): $RPATH/libcupti.so.11.1 not found in packages, sysroot(s) nor the missing_dso_whitelist.
2020-11-05T19:47:11.2526306Z .. is this binary repackaging?
```

We no longer ship the libraries that depended on `libcupti` so we no longer get this warning, but we're still not shipping the `libcupti` shared library and we should be.

I'm not sure of the state of the package on Windows.

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #40

### CODE REVIEW

**Comment by jaimergp** [comment]
I think this is ready for review @conda-forge/cudatoolkit!

**Comment by jakirkham** [comment]
Thanks Jaime! 😄

Should we add some kind of test for this change?

**Review by kkraus14 — APPROVED** [review]
LGTM

Agreed with John a test would be good to ensure we're packaging the libs as expected and not packaging the header(s).

**Comment by jaimergp** [comment]
I'll try to add that `cupti_profiler` package for the tests!

**Comment by jakirkham** [comment]
I think just doing a simple file existence test should be sufficient. While compiling an example in the tests would be nice, don’t think that is strictly necessary. Thanks for looking into this Jaime! 😀

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
Test lgtm, but will let @jakirkham take a look before merging

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Jaime! 😄

**Pull request merged**
