### PR TITLE
Release 11.7.0

### PR DESCRIPTION
**Pull request by bdice**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Followed the example of https://github.com/conda-forge/cudatoolkit-feedstock/pull/75.
It looks like the build number wasn't reset to 0 in previous PRs, so I didn't do that here either.
See also: https://conda-forge.org/docs/maintainer/knowledge_base.html#adding-support-for-a-new-cuda-version

### CODE REVIEW

**Comment by bdice** [comment]
@conda-forge-admin, please re-render

**Review by jakirkham — APPROVED** [review]
Thanks Bradley! 😄

**Comment by jakirkham** [comment]
Note [one CI build]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=508893&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642 ) failed due to HTTP issue with Conda. Will restart the failed job after others complete

**Comment by jakirkham** [comment]
Restarting CI

**Pull request merged**
