### PR TITLE
Adapt post-link scripts to escape spaces in PREFIX path

### LINKED ISSUE #51: White space in PREFIX path leads to .messages.txt being created in the wrong location
### Issue
When
```
conda config --add channels conda-forge
conda config --set channel_priority strict
conda create -p "C:\Program Files\test\" python==3.6 cudatoolkit==10.1.243
```
the message that is intended to be printed as part of the [post-link script](https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html), i.e. _"By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html"_, is written to a file named _C:\Program_.

As a result, the message that is intended to be printed is not printed after all actions are completed, i.e. as an add-on to _Executing transaction_. In addition, this file is not deleted since conda is looking for C:\Program Files\test\\.messages.txt.

### Possible Solution
PR follows.
 
<br/>
Environment (<code>conda list</code>):
<details>

```
Not relevant.

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
active environment : base
active env location : C:\ProgramData\Miniconda3
shell level : 1
user config file : C:\Users\m1fsche\.condarc
populated config files : C:\Users\m1fsche\.condarc
conda version : 4.8.2
conda-build version : not installed
python version : 3.7.6.final.0
virtual packages : __cuda=10.1
base environment : C:\ProgramData\Miniconda3  (writable)
channel URLs : https://conda.anaconda.org/conda-forge/win-64
                         https://conda.anaconda.org/conda-forge/noarch
                         https://repo.anaconda.com/pkgs/main/win-64
                         https://repo.anaconda.com/pkgs/main/noarch
                         https://repo.anaconda.com/pkgs/r/win-64
                         https://repo.anaconda.com/pkgs/r/noarch
                         https://repo.anaconda.com/pkgs/msys2/win-64
                         https://repo.anaconda.com/pkgs/msys2/noarch
package cache : C:\ProgramData\Miniconda3\pkgs
                           C:\Users\m1fsche\.conda\pkgs
                           C:\Users\m1fsche\AppData\Local\conda\conda\pkgs
envs directories : C:\ProgramData\Miniconda3\envs
                            C:\Users\m1fsche\.conda\envs
                            C:\Users\m1fsche\AppData\Local\conda\conda\envs
platform : win-64
user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
administrator : True
netrc file : None
offline mode : False
```
</details>

### Related
https://github.com/conda-forge/cudnn-feedstock/issues/12

### PR DESCRIPTION
**Pull request by FelixS90**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #51 .

### CODE REVIEW

**Comment by FelixS90** [comment]
> Hi! This is the friendly automated conda-forge-linting service.
> 
> I wanted to let you know that I linted all conda-recipes in your PR (`recipe`) and found some lint.
> 
> Here's what I've got...
> 
> For **recipe**:
> 
> * The recipe `license` should not include the word "License".
> 
> For **recipe**:
> 
> * License is not an SPDX identifier (or a custom LicenseRef) nor an SPDX license expression.
> 
> Documentation on acceptable licenses can be found [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#spdx-identifiers-and-expressions).

Not sure what I should do about this.

**Comment by kkraus14** [comment]
That can be ignore for now, thanks @FelixS90

**Review by kkraus14 — APPROVED** [review]

**Comment by kkraus14** [comment]
LGTM, will merge once CI passes, thanks!

**Comment by kkraus14** [comment]
@FelixS90 actually, you need to bump the build number in the recipe before we can merge, apologies!

**Comment by kkraus14** [comment]
@jakirkham in order to get this fix into previous versions of the toolkits do we need to cycle through the version in the recipe in follow up PRs as well? This is painful...

**Comment by jakirkham** [comment]
Nope we added a build matrix ( https://github.com/conda-forge/cudatoolkit-feedstock/pull/31 ). So this should already build all versions.

**Comment by jakirkham** [comment]
Thanks Felix for the PR and Keith for the review! 😄

**Comment by jakirkham** [comment]
@FelixS90 it looks like that didn't bump the build number. Could you please submit a PR to do that? Thanks! 😄

**Comment by jakirkham** [comment]
For context, [this is the build number]( https://github.com/conda-forge/cudatoolkit-feedstock/blob/d2bb6f72d756f3ea9c8f0dde5d23e44fc0ae8b2c/recipe/meta.yaml#L218 )

**Pull request merged**
