### PR TITLE
9.2

### PR DESCRIPTION
**Pull request by scopatz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Initial 9.2 recipe

### CODE REVIEW

**Comment by scopatz** [comment]
@cudatoolkit, this is ready for review! It is based on the 10.0 branch

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Anthony! 😄

**Comment by jaimergp** [comment]
Windows build was not uploaded here.

**Comment by scopatz** [comment]
Thanks @jaimergp - yeah, I think conda-forge is having issues with uploads right now. I restarted the job

**Comment by scopatz** [comment]
@conda-forge/cudatoolkit - any objections to merging this branch with master, since this branch is what should be forked from?

**Comment by kkraus14** [comment]
> @conda-forge/cudatoolkit - any objections to merging this branch with master, since this branch is what should be forked from?

none from me

**Comment by jakirkham** [comment]
I was planning to send PRs to update all branches with the CUDA 9.2 content

**Comment by scopatz** [comment]
I need to fix some of these sysroot_linux-64 issues, so I can do that today as part of that, if you want @jakirkham

**Comment by jakirkham** [comment]
Sounds good 🙂

**Pull request merged**
