### PR TITLE
Drop `cuinj64` and `accinj64` libraries

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/cudatoolkit-feedstock/issues/30

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by isuruf** [comment]
Are we not allowed to redistribute these? If not, we should delete all the existing packages.

**Comment by kkraus14** [comment]
> Are we not allowed to redistribute these? If not, we should delete all the existing packages.

We aren't, but I think the lack of including these in the EULA is moreso surrounding them not having any real use outside of the profilers distributed by NVIDIA.

If deleting the packages requires any real effort or is problematic in any way then I'm okay with leaving them inplace for now until someone asks us to remove them. If that ask comes and they question why things weren't deleted then we can happily link to this comment where I, an NVIDIA employee, guided the community in this direction.

**Comment by kkraus14** [comment]
@jakirkham changes LGTM. Would it be possible to add a test that asserts that these libs aren't in the package?

**Comment by isuruf** [comment]
Thanks @kkraus4. I think it's okay to delete them as they weren't published to main. ccing @conda-forge/core for thoughts.

Btw, can someone go through all the files and check that they are covered by the EULA?

**Comment by beckermr** [comment]
Go ahead and delete away!

**Comment by kkraus14** [comment]
> Btw, can someone go through all the files and check that they are covered by the EULA?

I'm going through now.

**Comment by kkraus14** [comment]
> > Btw, can someone go through all the files and check that they are covered by the EULA?
> 
> I'm going through now.

Went through and the only library we're packaging that's not included in the EULA is `libcusolverMg.so`. This feels like an oversight in the EULA so have reached out internally before we remove the package.

**Comment by leofang** [comment]
I have a perhaps very silly question 😅 If NVIDIA is (obviously) supportive behind all these efforts, can't we safely ignore EULA and do whatever we think is best for the community?

**Comment by kkraus14** [comment]
> I have a perhaps very silly question 😅 If NVIDIA is (obviously) supportive behind all these efforts, can't we safely ignore EULA and do whatever we think is best for the community?

Unfortunately we are still beholden to our legal department and ultimately they could demand things get removed regardless of our involvement / protest.

I'm all for us continuing to package things reasonably when there's questions regarding the EULA, but it's best to have us (NVIDIA) pre-emptively start conversations as opposed to knowingly continue against the EULA.

**Review by kkraus14 — APPROVED** [review]

**Comment by jakirkham** [comment]
Going to go ahead and merge while we are still figuring out `libcusolverMg.so`. Also deleted all of the existing `cudatoolkit` packages.

**Comment by jakirkham** [comment]
> Also deleted all of the existing `cudatoolkit` packages.

Unfortunately this caused Anaconda.org to forget all of the package details as we saw in issue ( https://github.com/conda-forge/cudatoolkit-feedstock/issues/2 ). Am going to repeat the same process of downloading the packaging manually uploading it again as described here ( https://github.com/conda-forge/cudatoolkit-feedstock/issues/2#issuecomment-708652960 ) to fix that issue.

**Comment by jakirkham** [comment]
Ok so the description is fixed if the package is `main`. However as soon as I move it to the `test` label it goes away. Not sure if there is a good way for us to fix this.

**Comment by jakirkham** [comment]
I've stuck packages under the `test` label for now. This seems to be the least of two evils atm. Happy to revisit if either someone can provide a better solution or we decide to move packages to the `main` label and still have issues.

**Comment by jakirkham** [comment]
Downloaded the `9.2` package right after CI published it to `main` from the merged PR ( https://github.com/conda-forge/cudatoolkit-feedstock/pull/44 ) and reuploaded it just now to make sure the UI render correctly ( https://github.com/conda-forge/cudatoolkit-feedstock/issues/2 ). Looks like it is working correctly again 🎉

Screen Shot 2020-11-25 at 7 11 44 PM

**Pull request merged**
